<html lang="en-US"><head>
    <meta charset="UTF-8">

<!-- Begin Jekyll SEO tag v2.6.1 -->
<title>Welcome to PangitSiAte! | Pangit si ate</title>
<meta name="generator" content="Jekyll v3.8.5">
<meta property="og:title" content="Welcome to PangitSiAte!">
<meta property="og:locale" content="en_US">
<link rel="canonical" href="https://zyxrath.github.io/trollwebsite/">
<meta property="og:url" content="https://zyxrath.github.io/trollwebsite/">
<meta property="og:site_name" content="trollwebsite">
<script type="application/ld+json">
{"@type":"WebSite","url":"https://zyxrath.github.io/trollwebsite/","name":"trollwebsite","headline":"Welcome to PangitSiAte!","@context":"https://schema.org"}</script>
<!-- End Jekyll SEO tag -->

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="theme-color" content="#157878">
    <link rel="stylesheet" href="/trollwebsite/assets/css/style.css?v=0990d1d56346e62e6455827fa649b66fd9ac55f6">
  </head>
  <body>
    <section class="page-header">
      <h1 class="project-name">trollwebsite</h1>
      <h2 class="project-tagline"></h2>
      
        
      
      
    </section>

    <section class="main-content">
      <h2 id="welcome-to-pangitsiate">Welcome to PangitSiAte!</h2>

<p>You can use the <a href="https://github.com/Zyxrath/trollwebsite/edit/master/README.md">editor on GitHub</a> to maintain and preview the content for your website in Markdown files.</p>

<p>Whenever you commit to this repository, GitHub Pages will run <a href="https://jekyllrb.com/">Jekyll</a> to rebuild the pages in your site, from the content in your Markdown files.</p>

<h3 id="markiplier">Markiplier</h3>

<p>Markiplier is a lightweight and easy-to-use syntax for styling your writing. It includes conventions for</p>

<div class="language-markdown highlighter-rouge"><div class="highlight"><pre class="highlight"><code>Syntax highlighted code block
hello
<span class="gh"># Header 1</span>
<span class="gu">## Header 2</span>
<span class="gu">### Header 3</span>
<span class="p">
-</span> Bulleted
<span class="p">-</span> List
<span class="p">
1.</span> Numbered
<span class="p">2.</span> List

<span class="gs">**Bold**</span> and _Italic_ and <span class="sb">`Code`</span> text

<span class="p">[</span><span class="nv">Link</span><span class="p">](</span><span class="sx">url</span><span class="p">)</span> and !<span class="p">[</span><span class="nv">Image</span><span class="p">](</span><span class="sx">src</span><span class="p">)</span>
</code></pre></div></div>

<p>For more details see <a href="https://guides.github.com/features/mastering-markdown/">GitHub Flavored Markdown</a>.</p>

<h3 id="jekyll-themes">Jekyll Themes</h3>

<p>Your Pages site will use the layout and styles from the Jekyll theme you have selected in your <a href="https://github.com/Zyxrath/trollwebsite/settings">repository settings</a>. The name of this theme is saved in the Jekyll <code class="language-plaintext highlighter-rouge">_config.yml</code> configuration file.</p>

<h3 id="support-or-contact">Support or Contact</h3>

<p>Having trouble with Pages? Check out our <a href="https://help.github.com/categories/github-pages-basics/">documentation</a> or <a href="https://github.com/contact">contact support</a> and we’ll help you sort it out.</p>


      <footer class="site-footer">
        
          
        
        
      </footer>
    </section>

    
  

</body></html>
